### ISSUE TITLE
Add support/functionality for AcceptableValueRange and AcceptableValueList.

### ISSUE THREAD

**Issue by JohnEdwa** [MapleWheels/BepInEx_Extensions#1]
These are the functions BepinEx is designed to use for creating configuration files that can be then easily parsed and modified by extrenal things, such as mod managers.

Here's the [snippet from BepinEx Configuration Manager readme](https://github.com/BepInEx/BepInEx.ConfigurationManager#how-to-make-my-setting-into-a-slider), and here is the [API documentation page](https://bepinex.github.io/bepinex_docs/master/api/BepInEx.Configuration.AcceptableValueList-1.html).

**Comment by MapleWheels** [comment]
These will be added with the next release. Please check the milestones for release date estimates (current ETA is Monday, September 14, 2020.

**Comment by MapleWheels** [comment]
Fixed during the rewrite of the library.
