### ISSUE TITLE
NewPipe old UI

### ISSUE THREAD

**Issue by Isayso** [MapleWheels/BepInEx_Extensions#3]
Had the same need, did a fork. Please try it. I'm not sure if I can do it all the time, the guys are changing the APIs frequently and to find out what is time consuming. Have fun!

[NewPipe19.9.apk.zip](https://github.com/MapleWheels/BepInEx_Extensions/files/5456815/NewPipe19.9.apk.zip)

**Comment by MapleWheels** [comment]
Wrong repo lol.
